[package]
name = "cyma"
version = "0.1.0"
edition = "2021"
description = "Composable views and associated data structures for nih-plug UIs made using VIZIA"

[dependencies]
nih_plug_vizia = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
num-traits = "0.2.18"
len-trait = "0.6.1"

[dev-dependencies]
rand = "0.8.5"
